"""production_company_mappings.py"""
"""Mapping production companies to home countries"""

import pandas as pd

# =============================================================================
# HIGH CONFIDENCE MAPPINGS
# Major studios and well-known production companies with verifiable headquarters
# =============================================================================

high_confidence = {
    # US Major Studios
    'Universal Pictures': 'US',
    'Paramount Pictures': 'US',
    'Twentieth Century Fox Film Corporation': 'US',
    'Columbia Pictures': 'US',
    'Columbia Pictures Corporation': 'US',
    'New Line Cinema': 'US',
    'Miramax Films': 'US',
    'Fox Searchlight Pictures': 'US',
    'Walt Disney Pictures': 'US',
    'Walt Disney': 'US',
    'DreamWorks SKG': 'US',
    'DreamWorks': 'US',
    'Warner Bros.': 'US',
    'Warner Bros. Pictures': 'US',
    'Metro-Goldwyn-Mayer (MGM)': 'US',
    'United Artists': 'US',
    'TriStar Pictures': 'US',
    'Sony Pictures': 'US',
    'Sony Pictures Classics': 'US',
    'Touchstone Pictures': 'US',
    'Hollywood Pictures': 'US',
    '20th Century Fox': 'US',
    '20th Century Fox Home Entertainment': 'US',
    'Fox 2000 Pictures': 'US',
    'Screen Gems': 'US',
    'Focus Features': 'US',
    'Gramercy Pictures': 'US',
    'Fine Line Features': 'US',
    'USA Films': 'US',
    'October Films': 'US',
    'Buena Vista': 'US',
    'DisneyToon Studios': 'US',
    'Village Roadshow Pictures': 'US',
    'Lionsgate': 'US',
    'Lions Gate Films': 'US',
    'Lions Gate Family Entertainment': 'US',
    'Summit Entertainment': 'US',
    'The Weinstein Company': 'US',
    'Weinstein Company, The': 'US',
    'Regency Enterprises': 'US',
    'Legendary Pictures': 'US',
    'Amblin Entertainment': 'US',
    'Lucasfilm': 'US',
    'Marvel Studios': 'US',
    'Participant Media': 'US',
    'Relativity Media': 'US',
    'Amazon Studios': 'US',
    'Millennium Films': 'US',
    'Nu Image Films': 'US',
    'Spyglass Entertainment': 'US',
    'Lakeshore Entertainment': 'US',
    'Alcon Entertainment': 'US',
    'Dune Entertainment': 'US',
    'Intermedia Films': 'US',
    'Franchise Pictures': 'US',
    'Cinergi Pictures Entertainment': 'US',
    'Revolution Studios': 'US',
    'Mandalay Pictures': 'US',
    'Dimension Films': 'US',
    'Rogue Pictures': 'US',
    'Destination Films': 'US',
    'Dark Castle Entertainment': 'US',
    'Ghost House Pictures': 'US',
    'Twisted Pictures': 'US',
    'Cross Creek Pictures': 'US',
    'Bold Films': 'US',
    'FilmNation Entertainment': 'US',
    'Endgame Entertainment': 'US',
    'Sidney Kimmel Entertainment': 'US',
    'River Road Entertainment': 'US',
    'Mandate Pictures': 'US',
    'Paramount Vantage': 'US',
    '2929 Productions': 'US',
    'Plan B Entertainment': 'US',
    'Imagine Entertainment': 'US',
    'Scott Free Productions': 'US',
    'American Zoetrope': 'US',
    'Jerry Bruckheimer Films': 'US',
    'Silver Pictures': 'US',
    'Centropolis Entertainment': 'US',
    'Centropolis Film Productions': 'US',
    'Impact Pictures': 'US',
    'Epsilon Motion Pictures': 'US',
    'The Mark Gordon Company': 'US',
    'Laurence Mark Productions': 'US',
    'Gravier Productions': 'US',
    'Atlas Entertainment': 'US',
    'Original Film': 'US',
    'GK Films': 'US',
    'Likely Story': 'US',
    'Mike Zoss Productions': 'US',
    'Double Feature Films': 'US',
    'De Line Pictures': 'US',
    'Di Bonaventura Pictures': 'US',
    'Saturn Films': 'US',
    'Vertigo Entertainment': 'US',
    '1492 Pictures': 'US',
    'Section Eight': 'US',
    'Appian Way': 'US',
    'The Kennedy/Marshall Company': 'US',
    'Lightstorm Entertainment': 'US',
    'Killer Films': 'US',
    'Davis Entertainment': 'US',
    'The Zanuck Company': 'US',
    'Geffen Pictures': 'US',
    'Broadway Video': 'US',
    '21 Laps Entertainment': 'US',
    'Jim Henson Productions': 'US',
    'Motion Picture Corporation of America': 'US',
    'Motion Picture Corporation of America (MPCA)': 'US',
    'HBO': 'US',
    'Home Box Office (HBO)': 'US',
    'NBC': 'US',
    'Universal TV': 'US',
    'MTV Films': 'US',
    'CBS Films': 'US',
    'Turner Network Television': 'US',
    'Lifetime Television': 'US',
    'DC Comics': 'US',
    'Magnolia Pictures': 'US',
    'Janus Films': 'US',

    # UK
    'BBC Films': 'GB',
    'British Broadcasting Corporation (BBC)': 'GB',
    'BBC Worldwide': 'GB',
    'BBC Wales': 'GB',
    'Working Title Films': 'GB',
    'Channel Four Films': 'GB',
    'Film4': 'GB',
    'Film 4': 'GB',
    'UK Film Council': 'GB',
    'Film Council': 'GB',
    'Ingenious Film Partners': 'GB',
    'Ingenious Media': 'GB',
    'PolyGram Filmed Entertainment': 'GB',
    'Eon Productions': 'GB',
    'Pathé Pictures International': 'GB',
    'DNA Films': 'GB',
    'Hammer Film Productions': 'GB',
    'Icon Entertainment International': 'GB',
    'The Rank Organisation': 'GB',
    'Ecosse Films': 'GB',
    'Revolution Films': 'GB',
    'Isle of Man Film': 'GB',
    'Tiger Aspect Productions': 'GB',
    'Recorded Picture Company (RPC)': 'GB',
    'Recorded Pictures Company': 'GB',
    'Goldcrest Films International': 'GB',
    'Aardman Animations': 'GB',
    'Ealing Studios': 'GB',
    'Big Talk Productions': 'GB',
    'Renaissance Films': 'GB',
    'Merchant Ivory Productions': 'GB',
    'Heyday films': 'GB',

    # France
    'France 2 Cinéma': 'FR',
    'France 3 Cinéma': 'FR',
    'StudioCanal': 'FR',
    'Studio Canal': 'FR',
    'Le Studio Canal+': 'FR',
    'Gaumont': 'FR',
    'Pathé': 'FR',
    'Pathé Films': 'FR',
    'Pathé Renn Productions': 'FR',
    'EuropaCorp': 'FR',
    'Europa Corp': 'FR',
    'Wild Bunch': 'FR',
    'Canal Plus': 'FR',
    'Canal+': 'FR',
    'Arte': 'FR',
    'Arte France': 'FR',
    'ARTE France Cinéma': 'FR',
    'Davis-Films': 'FR',
    'Celluloid Dreams': 'FR',
    'Bac Films': 'FR',
    'Pyramide Productions': 'FR',
    'Paradis Films': 'FR',
    'Renn Productions': 'FR',
    'Pan Européenne Production': 'FR',
    'Les Films du Losange': 'FR',
    'MACT Productions': 'FR',
    'Les Films Alain Sarde': 'FR',
    'Eskwad': 'FR',
    'Haut et Court': 'FR',
    'La Petite Reine': 'FR',
    'Eurimages': 'FR',
    'Procirep': 'FR',
    'TF1 Films Productions': 'FR',
    'Why Not Productions': 'FR',
    'Ciby 2000': 'FR',
    'MK2 Productions': 'FR',

    # Germany
    'Studio Babelsberg': 'DE',
    'Senator Film Produktion': 'DE',
    'Constantin Film': 'DE',
    'Boll Kino Beteiligungs GmbH & Co. KG': 'DE',
    'Pandora Filmproduktion': 'DE',
    'Beta Film': 'DE',
    'Universum Film (UFA)': 'DE',
    'Bavaria Film': 'DE',
    'Werner Herzog Filmproduktion': 'DE',
    'Bayerischer Rundfunk': 'DE',
    'Degeto Film': 'DE',
    'X-Filme Creative Pool': 'DE',
    'Wiedemann & Berg Filmproduktion': 'DE',

    # Other Europe
    'Zentropa Entertainments': 'DK',
    'Zentropa Productions': 'DK',
    'Det Danske Filminstitut': 'DK',
    'Danmarks Radio (DR)': 'DK',
    'Nimbus Film Productions': 'DK',
    'Nordisk Film': 'DK',
    'Danish Film Institute': 'DK',
    'Film i Väst': 'SE',
    'Sandrews': 'SE',
    'Sveriges Television (SVT)': 'SE',
    'Svenska Filminstitutet': 'SE',
    'Rai Cinema': 'IT',
    'BIM Distribuzione': 'IT',
    'Medusa Film': 'IT',
    'Fandango': 'IT',
    'Cattleya': 'IT',
    'Mikado Film': 'IT',
    'Televisión Española (TVE)': 'ES',
    'Telecinco Cinema': 'ES',
    'Morena Films': 'ES',
    'Filmax Entertainment': 'ES',
    'Filmax': 'ES',
    'Sogecine': 'ES',
    'El Deseo': 'ES',
    'Antena 3 Films': 'ES',
    'Samsa Film': 'LU',
    'Proton Cinema': 'HU',
    'Castel Film Romania': 'RO',
    'Coop 99': 'AT',
    'Les Films Du Fleuve': 'BE',
    'Polish Film Institute': 'PL',
    'Helsinki Filmi Oy': 'FI',
    'Matila Röhr Productions (MRP)': 'FI',
    'Finnish Film Foundation': 'FI',
    'Yleisradio (YLE)': 'FI',
    'Central Partnership': 'RU',
    'Bazelevs Production': 'RU',
    'Channel One Russia': 'RU',

    # Asia
    'Toho Company': 'JP',
    'JVC Entertainment': 'JP',
    'Bandai Visual Company': 'JP',
    'TV Tokyo': 'JP',
    'Kurosawa Production Co.': 'JP',
    'Namco': 'JP',
    'Toei Animation': 'JP',
    'Emperor Motion Pictures': 'HK',
    'Edko Films': 'HK',
    'Media Asia Films': 'HK',
    'Lion Rock Productions': 'HK',
    'Applause Pictures': 'HK',
    'Golden Harvest Company': 'HK',
    'Shanghai Film Group': 'CN',
    'China Film Group': 'CN',
    'Enlight Pictures': 'CN',
    'Huayi Brothers': 'CN',
    'CJ Entertainment': 'KR',
    'Eros International': 'IN',
    'Yash Raj Films': 'IN',
    'UTV Motion Pictures': 'IN',

    # Oceania
    'Bazmark Films': 'AU',
    'Australian Film Finance Corporation': 'AU',
    'South Australian Film Corporation': 'AU',
    'WingNut Films': 'NZ',
    'New Zealand Film Commission': 'NZ',
    'South Pacific Pictures': 'NZ',

    # Canada
    'Rhombus Media': 'CA',
    'Alliance Films': 'CA',
    'Copperheart Entertainment': 'CA',
    'Alliance Atlantis Communications': 'CA',
    'Téléfilm Canada': 'CA',
    'Brightlight Pictures': 'CA',
    'Prodigy Pictures': 'CA',
    'National Film Board of Canada (NFB)': 'CA',

    # Other
    'Irish Film Board': 'IE',
    'Element Pictures': 'IE',
    'Cartoon Saloon': 'IE',
    'O2 Filmes': 'BR',
    'Mantarraya Producciones': 'MX',
}

# =============================================================================
# LOW CONFIDENCE MAPPINGS
# Smaller companies where home country is inferred from name/context
# =============================================================================

low_confidence = {
    # Companies with multiple films
    'Delux Productions': 'LU',
    'Rising Star': 'US',
    'uFilm': 'BE',
    'Matador Pictures': 'US',
    'New Amsterdam Entertainment': 'US',
    'Angoa-Agicoa': 'FR',
    'Arcadia Motion Pictures': 'US',
    'Denver and Delilah Productions': 'US',
    'Match Factory, The': 'DE',
    'Rainmaker Entertainment': 'CA',
    'NGN Productions': 'CA',
    'Irish Dreamtime': 'US',
    'Jeff Most Productions': 'US',
    'Kintop Pictures': 'DE',
    'First Floor Features': 'NL',
    'Carousel Picture Company': 'GB',
    'Distant Horizons': 'ZA',
    'Film House Bas Celik': 'RS',
    'Egoli Tossell Film AG': 'DE',
    'Octagon Films': 'IE',
    'Atmo Media Network': 'SE',
    '100 Bares': 'AR',
    'Beijing New Picture Film Co. Ltd.': 'CN',
    'Andrew Stevens Entertainment': 'US',
    'North by Northwest Entertainment': 'CA',
    'International Production Company': 'RU',
    'Onyx Films': 'FR',
    'Current Entertainment': 'US',
    'The Javelina Film Company': 'US',
    'TLA Releasing': 'US',
    'Ultra Films': 'MX',
    'Sofica Valor 6': 'FR',
    'Live Entertainment': 'US',
    'Front Street Productions': 'US',
    'Casey Silver Productions': 'US',

    # Single-film companies
    'Thunder Road Pictures': 'US',
    'Havoc': 'US',
    'The Movie Network (TMN)': 'CA',
    'Bergen Film': 'NO',
    'Comet Film Produktion GmbH': 'DE',
    'Lin Pictures': 'US',
    'Insight Film Studios': 'CA',
    'Caramel Films': 'ES',
    'Brillstein Entertainment Partners': 'US',
    'Making Movies Oy': 'FI',
    'Look Now': 'US',
    'Instinct Entertainment': 'AU',
    'Great Highway Company': 'US',
    'Johnson Production Group': 'US',
    'WTFilms': 'FR',
    'Gébéka Films': 'FR',
    'Sun Entertainment Culture': 'CN',
    'Reisenbauer Film': 'AT',
    'Les Productions du Trésor': 'FR',
    'Sonet Film': 'SE',
    'Mr. Mudd Production': 'US',
    'Wolper Organization': 'US',
    'CTV International': 'CA',
    'Vega Film': 'CH',
    'Parnasse Production': 'FR',
    'Jadran Film': 'HR',
    'Overseas FilmGroup': 'US',
    'Solar Films': 'FI',
    'Chernin Entertainment': 'US',
    'Aries [jp]': 'JP',
    'Lama Films': 'FR',
    'Craven-Maddalena Films': 'US',
    'Interlight': 'US',
    'Signature Pictures': 'US',
    'American Filmworks': 'US',
    'Odyssey Entertainment': 'US',
    'Ibermedia': 'ES',
    'Gospel of John Ltd.': 'CA',
    'GFT Entertainment': 'US',
    'Chartoff Productions': 'US',
    'Firm Films': 'GB',
    'Sandstorm Films': 'US',
    'Avenue Pictures Productions': 'US',
    'Hachette Première': 'FR',
    'Lou Yi Inc.': 'TW',
    'KSS': 'JP',
    'World 2000 Entertainment': 'RO',
    'Peninsula Films': 'AU',
    'Hubert Bals Fund': 'NL',
    'Cruise/Wagner Productions': 'US',
    'R&C Produzioni': 'IT',
    'Palace Pictures': 'GB',
    'Gruppo Minerva International': 'IT',
    'Braun Entertainment Group': 'US',
    'Von Vietinghoff Filmproduktion': 'DE',
    'Michael London Productions': 'US',
    'M&M Productions': 'US',
    'Silent Hill DCP Inc.': 'CA',
    'International Traders': 'US',
    'One Race Productions': 'US',
    'Capitol Films': 'GB',
    "Donners' Company": 'US',
    'Tree Line Films': 'US',
    'Patalex IV Productions Limited': 'GB',
    'Autonomous': 'GB',
    'R.P. Productions': 'FR',
    'Memfis Film': 'SE',
    'Gaylord Films': 'US',
    'Ang Lee Productions': 'US',
    'Lamb Bear Entertainment': 'US',
    'Lonely Film Productions GmbH & Co. KG.': 'DE',
    'Fireworks Pictures': 'CA',
    'Pathe Productions': 'GB',
    'August Entertainment': 'US',
    'Studio Trite': 'RU',
    'Timnick Films': 'US',
    'ContentFilm': 'GB',
    'Ensueño Films': 'ES',
    'Splendid Pictures': 'US',
    'Vía Digital': 'ES',
    'Fondo para la Producción Cinematográfica de Calidad (FOPROCINE)': 'MX',
    'Media Asia Film': 'HK',
    'Kim Ki-Duk Film': 'KR',
    'Happy End Filmproductions AB': 'SE',
    'Nu Image Entertainment': 'US',
    'Kanzaman': 'LB',
    'CoBo Fund': 'NL',
    'Muse Entertainment Enterprises': 'CA',
    'Tessalit Productions': 'FR',
    'Prospero Pictures': 'CA',
    'Defender Production': 'US',
    'Vanguard Films': 'US',
    'Emotion Pictures': 'AR',
    'Bedford Falls Productions': 'US',
    'MOOVIE - the art of entertainment GmbH': 'DE',
    'Estudios Picasso': 'ES',
    'Prophecy Pictures Ltd.': 'GB',
    'Tatira-Hiller Productions': 'US',
    'Kinokompaniya CTB': 'RU',
    'Blueprint Pictures': 'GB',
    'Future Film Group': 'GB',
    'Audley Films LLP': 'GB',
    'Block 2 Pictures': 'US',
    'Film Afrika': 'ZA',
    'Filmstiftung Nordrhein-Westfalen': 'DE',
    'Eclectic pictures': 'GB',
    'Saga Film': 'DK',
    'Mosaic Media Group': 'US',
    'HDNet Films': 'US',
    'Foresight Unlimited': 'US',
    'La Fabrique de Films': 'FR',
    'Grosvenor Park Films LLP': 'GB',
    'Bodega Films': 'FR',
    'Mikona Productions GmbH & Co. KG': 'DE',
    'Helkon Media AG': 'DE',
    'Kingsgate Films': 'GB',
    'Milagro Films': 'US',
    'Les Films du Lendemain': 'FR',
    'Manigolda Film': 'IT',
    'Huayi Brothers Media Corporation': 'CN',
    'Palomar Pictures': 'US',
    'Les Films du Poisson': 'FR',
    'Exodus Film Group': 'US',
    'Grosvenor Park Media Ltd.': 'GB',
    'A. Film': 'DK',
    'CD Films': 'ES',
    'Myriad Pictures': 'US',
    "Les Films d'Ici": 'FR',
    'CB Films': 'ES',
    'Lietuvos Kinostudija': 'LT',
    'Columbia TriStar Nordisk Film Distributors A/S': 'DK',
    'Portobello Pictures': 'GB',
    'Cinerenta Medienbeteiligungs KG': 'DE',
    'HAL Films': 'JP',
    'ABS-CBN Film Productions': 'PH',
    'Newmarket Capital Group': 'US',
    'Producciones Anhelo': 'ES',
    'Asymmetrical Productions': 'US',
    'Infinity Features Entertainment': 'US',
    'Senator Entertainment Co': 'DE',
    'Nouvelles Éditions de Films (NEF)': 'FR',
    'Revelations Entertainment': 'US',
    'Surreel': 'US',
    'Ascendant Pictures': 'US',
    'Be Good Productions': 'US',
    'Larger Than Life Productions': 'AU',
    'Dan Films': 'GB',
    'Niama Film': 'BF',
    'Insight Productions': 'CA',
    'Valkyrie Films': 'US',
    'Rainmark Films': 'US',
    'Ashutosh Gowariker Productions': 'IN',
    'Grand Army Entertainment': 'US',
    'Silverline Pictures': 'US',
    'Phoenician Entertainment': 'US',
    'Steamroller Productions': 'US',
    'ArieScope Pictures': 'US',
    'Project One Films': 'US',
    'Mandarin Films Distribution Co.': 'HK',
    'Se-ma-for Studios': 'PL',
    'Barna-Alper Productions': 'CA',
    'Studio 37': 'FR',
    'KSM Film': 'DE',
    'Microsoft': 'US',
    '3L Filmproduktion GmbH': 'DE',
    'Six Entertainment': 'US',
    'APT Films': 'US',
    'Devonshire Productions': 'US',
    'MT2 Services': 'US',
    'PFI Studios': 'GB',
    'Apipoulaï': 'FR',
    'Adlabs Films Ltd.': 'IN',
    'Crystal Sky Worldwide': 'US',
    'Gold/Miller Productions': 'US',
    'Bungalow Productions': 'US',
    'Industry Entertainment': 'US',
    'Granada Film Productions': 'GB',
    'Battleplan Productions': 'CA',
    'Fifth Avenue Entertainment': 'US',
    'Amen Ra Films': 'US',
    'New Oz Productions': 'AU',
    'Bluetree Pictures': 'US',
    'This Is That Productions': 'US',
    'Strike Entertainment': 'US',
    'Douek Productions': 'US',
    'Starz Animation': 'CA',
    'Eddie Saeta': 'ES',
    'Tarentula': 'BE',
    'Aurora Films': 'FR',
    'Boram Entertainment Inc.': 'KR',
    'Eden Rock Media': 'US',
    'Bona Entertainment': 'CN',
    'Mockingbird Pictures': 'US',
    'Serendipity Point Films': 'CA',
    'Christal Films': 'CA',
    'X Filme International': 'DE',
    'Quad Productions': 'FR',
    'ApolloMovie Beteiligungs': 'DE',
    'AVEK': 'FI',
    'Irish Screen': 'IE',
    'Japan America Picture Company': 'JP',
    'Egg Pictures': 'US',
    '21st Century Film Corporation': 'US',
    'American Playhouse': 'US',
    'Figment Films': 'GB',
    'CanWest Global Communications Corporationt': 'CA',
    'Fox Entertainment Group': 'US',
    'Camera': 'ES',
    'TV2': 'DK',
    'Skopia Film': 'NO',
    'CTR': 'DE',
    'Asghar Farhadi Productions': 'IR',
    'GNK Productions': 'US',
    'experiences films': 'FR',
    'Moonlighting Films': 'GB',
    'Quinta Communications': 'FR',
    'Lookout Films': 'DE',
    'Filmes do Tejo': 'PT',
    'Neue Road Movies': 'DE',
    'Hofmann & Voges Entertainment': 'DE',
    'TS Productions': 'FR',
    'Nikolaus Geyrhalter Filmproduktion': 'AT',
    'T.H.E. Films': 'US',
    'Stardust Pictures': 'US',
    'Blind Spot Pictures Oy': 'FI',
    'Max TV': 'HR',
    'Capital Arts Entertainment': 'US',
    'Diaphana Films': 'FR',
    'Darclight': 'US',
    'Instinctive Film': 'GB',
    'Universal Pictures International (UPI)': 'US',
    'Chrysalis Films': 'GB',
    'Voltage pictures': 'US',
    'Razor Film Produktion GmbH': 'DE',
    'Warner Premiere': 'US',
    'Corrino Media Corporation': 'CA',
    'Cliffjack Motion Pictures': 'US',
    'ARP Sélection': 'FR',
    'The Asylum': 'US',
    'Arcade Pictures': 'US',
    'Anarchos Productions': 'US',
    'Access Pictures': 'US',
    'SND': 'FR',
    'Nord-Ouest Productions': 'FR',
    'First Generation Films': 'CA',
    'Sarke Studio': 'NO',
    'Buffalo Gal Pictures': 'CA',
    'Walt Disney Television Animation': 'US',
    'New Horizons': 'US',
    'Parabolic Pictures': 'US',
    'Canal Sur Televisión': 'ES',
    'Centre National de la Cinématographie': 'FR',
    'Elle Driver': 'FR',
    'Memento Films Production': 'FR',
    'Boll KG': 'DE',
    'Social Capital': 'US',
    'Cloud Eight Films': 'GB',
    'RabbitBandini Productions': 'US',
    'Quite Nice Pictures': 'GB',
    'Spring Films': 'GB',
    'Canal+Polska': 'PL',
    'China Star Entertainment': 'HK',
    'Variance Films': 'US',
    'Taska Film': 'EE',
    'Capelight Pictures': 'DE',
    'Huaxia Film Distribution Company': 'CN',
    'Pictures in Paradise': 'AU',
    'Eagle Vision Inc.': 'CA',
    'Archer Street Productions': 'GB',
    'Pandora Film': 'DE',
    'Edith Film Oy': 'FI',
    'Vnesheconombank': 'RU',
    'Studio Hamburg International Production': 'DE',
    'Sonet Film AB': 'SE',
    'Fickle Fish Films': 'US',
    'Fastnet Films': 'IE',
    '3311 Productions': 'US',
    'Studio Hamburg Filmproduktion': 'DE',
    'Baltic Film Group': 'LT',
    'F G Film Productions': 'US',
    'Caméra One': 'FR',
    'Prana Animation Studios': 'IN',
    'IM Global': 'US',
    'Red Lamp Films': 'GB',
    'Thema Production': 'FR',
    'Valve': 'US',
    'Scottish Screen': 'GB',
    '120dB Films': 'NL',
    'Wonderland Sound and Vision': 'US',
    'Le Pacte': 'FR',
    'Epithète Films': 'FR',
    'Independent Moving Productions Inc. (IMPinc.)': 'CA',
    'Aegis Film Fund': 'GB',
    'Before the Door Pictures': 'US',
    'FilmFernsehFonds Bayern': 'DE',
    'Angel Entertainment': 'US',
    'Hobby Films': 'ES',
    'Bookshop Productions': 'US',
    'Fountainbridge Films': 'GB',
    'Arts Council of England': 'GB',
    'Carousel Picture Company, The': 'GB',
    'Spring Creek Productions': 'US',
    'Medusa Produzione': 'IT',
    'Nordic Film': 'DK',
    'Kuzui Enterprises': 'JP',
    'Futurikon': 'FR',
    'Prospect Park': 'US',
    'Boku Films': 'FR',
    'Epidem': 'US',
    'Cine Bazar': 'JP',
    'Fidélité Productions': 'FR',
    'pixstar': 'DE',
    'Új Budapest Filmstudió': 'HU',
    'Odyssey Media': 'US',
    'Tatfilm': 'DE',
    'ZEILT productions': 'NL',
    'Ridley Scott Associates': 'GB',
    'Handle Productions': 'GB',
    'Perdido Productions': 'US',
    'Peace Arch Films': 'CA',
    'Eyeworks Touchdown': 'NL',
    'Pioneer Pictures': 'US',
    'Davis-Panzer Productions': 'US',
    'Future Films': 'GB',
    'Indigo Film': 'IT',
    'Ann and Phelim Media': 'IE',
    'Whiskers Post Production': 'NZ',
    'Wellington Films': 'GB',
    'Mandragora Movies': 'CZ',
    'Pegasus Motion Pictures': 'HK',
    'TinRes Entertainment': 'US',
    'Pallas Film': 'EE',
    'Hopscotch Features': 'AU',
    'After Dark Films': 'US',
    'Inspired Minority Pictures': 'IE',
    'Wildgaze Films': 'GB',
    'Alleycat Studios': 'US',
    'Filmhuset Gruppen': 'SE',
    'Nasser Group, North': 'US',
    'Cine Canibal': 'MX',
    'Corsan Productions': 'ES',
    'DDG': 'DE',
    'Silver Ant': 'CN',
    'Aristarain P.C.': 'AR',
    'Edward R. Pressman Film': 'US',
    'Integral Film': 'HR',
    'Redwood Palms Pictures': 'US',
    'Heavy Productions': 'US',
    'Worldview Entertainment': 'US',
    'WMG Film': 'US',
    'Media Max Productions': 'US',
    'One Eyed': 'US',
    'Eficine 226': 'MX',
    'CN Film': 'CN',
    'Gateway Films': 'US',
    'Nexus Factory': 'FR',
    'Head Gear Films': 'GB',
    'Qwerty Films': 'GB',
    'The Chimney Pot': 'SE',
    'Allegro-Film': 'AT',
    'Maipo Film- og TV Produksjon': 'NO',
    'Tiberius Film': 'DE',
    'NiKo Film': 'DE',
    'Rat Pack Filmproduktion': 'DE',
    'Zide-Perry Productions': 'US',
    'Extreme Video Snc': 'IT',
    'Kapara Pictures': 'US',
    'El Azar': 'ES',
    'Corsan': 'ES',
    'SC Films International': 'GB',
    'Infinitum Nihil': 'US',
    'Two Oceans Production': 'ZA',
    'United King Films': 'IL',
    'Metanoia Films': 'US',
    'Sepia Films': 'ES',
    'Thunder Perfect Mind': 'GB',
    'Pretty Pictures': 'FR',
    'Global Emerging Markets (GEM)': 'US',
    'Zinc Entertainment Inc.': 'CA',
    'Mili Pictures': 'CN',
    'Kinodel': 'RU',
    'Ciné Cri De Coeur': 'FR',
    'Bedlam Productions': 'GB',
    'Parts and Labor': 'US',
    'Majestic Filmproduktion': 'DE',
    'Skyline Entertainment': 'US',
    'HanWay Films': 'GB',
    'Filmförderungsanstalt (FFA)': 'DE',
    'Imagenation Abu Dhabi FZ': 'AE',
    'Alhena Films': 'ES',
    'Troma Entertainment': 'US',
    'Motlys': 'NO',
    'Entre Chien et Loup': 'BE',
    'Andrea Leone Films': 'US',
    'HI Film Productions': 'RO',
    'Blue Angels Films': 'FR',
    'Ombra Films': 'ES',
    'Purple Pictures': 'GB',
    'Handsomecharlie Films': 'US',
    'CatchPlay': 'TW',
    '27 Films Production': 'DE',
    'Lanzadera Films': 'ES',
    'Benaroya Pictures': 'US',
    'Caviar Films': 'BE',
    'Blue Pen Ltd.': 'GB',
    'Rhône-Alpes Cinéma': 'FR',
    'Tondero Producciones': 'PE',
    'Corporation for Public Broadcasting (CPB)': 'US',
    'Forecast Pictures': 'US',
    'Caracol Televisión': 'CO',
    'Red Letter Media': 'US',
    'Strata Studios': 'US',
    'Cool Cat Productions': 'US',
    'Les films du Worso': 'FR',
    'Canana Films': 'MX',
    'Pennebaker Hegedus Films, Inc.': 'US',
    'Whale Studio': 'CN',
    'Echo Lake Entertainment': 'US',
    'Enjoy Movies': 'IT',
    'Nepenthe Film': 'DE',
    'Illusion Entertainment Group': 'US',
    'Mirabai Films': 'US',
    'Constellation Films': 'US',
    'Vertigo Productions': 'GB',
    'Kopelson Entertainment': 'US',
    'Komuna': 'PL',
    'Tig Productions': 'US',
    'New South Wales Film & Television Office': 'AU',
    'Emote Productions': 'GB',
    'MA.JA.DE Fiction': 'DE',
    'Kinoproduction': 'FI',
    'LD Entertainment': 'US',
    'Timothy Burrill Productions': 'GB',
    '3D Content Hub': 'GB',
    'Wells & Jeta Entertainment': 'US',
    'RAMCO': 'FR',
    "Les Films de l'Astrophore": 'FR',
    'Cosmo-Films': 'FR',
    'Blinder Films': 'IE',
    'Viking Films': 'NO',
    'Red Giant Movies': 'IN',
    'Spectacle Entertainment Group': 'US',
    'Big Beach Films': 'US',
    'Periferia Production': 'FI',
    'Running Reel Films': 'US',
    'Lidderdalei Productions': 'US',
    'SBS Productions': 'FR',
    'Beijing Poly-bona Film Distribution Company': 'CN',
    'Don Films': 'FR',
    'Marubeni': 'JP',
    'Action House': 'US',
    'Indomitable Entertainment': 'US',
    'V. Creations': 'IN',
    'Hepp Film': 'SE',
    'InterTitle Films': 'US',
    'Detour Film Production': 'IE',
    'Five Mile River Films': 'US',
    'Scion Films': 'GB',
    'At Group': 'RU',
    'Cinevent': 'ES',
    'P.R. Productions': 'US',
    'SBS Films': 'KR',
    'Eastern Sunrise Films': 'US',
    'Blue Waters Motion Pictures': 'US',
    'Jungle Book Entertainment': 'US',
    'Telefe': 'AR',
    'Society Entertainment': 'US',
    'Orgon Films': 'US',
    'Independent Films': 'NL',
    'Shinework Media': 'CN',
    'FilmEngine': 'US',
    'Kasbah-Film Tanger': 'MA',
    'Balkan Film': 'RS',
    'Grindfist': 'US',
    'Beofilm': 'RS',
    'NEST Family Entertainment': 'US',
    'Trans-Film': 'DE',
    'Jerry Weintraub Productions': 'US',
}

# =============================================================================
# SAVE MAPPINGS
# =============================================================================

high_df = pd.DataFrame([
    {'company_name': k, 'home_country': v, 'confidence': 'high'}
    for k, v in high_confidence.items()
])

low_df = pd.DataFrame([
    {'company_name': k, 'home_country': v, 'confidence': 'low'}
    for k, v in low_confidence.items()
])

high_df.to_csv(
    "C:/Users/kurtl/PycharmProjects/gravity_model/data/processed/studio_mappings_high_confidence.csv",
    index=False
)

low_df.to_csv(
    "C:/Users/kurtl/PycharmProjects/gravity_model/data/processed/studio_mappings_low_confidence.csv",
    index=False
)

# =============================================================================
# SUMMARY
# =============================================================================

print("=== STUDIO MAPPINGS SUMMARY ===")
print(f"High confidence mappings: {len(high_df)}")
print(f"Low confidence mappings: {len(low_df)}")
print(f"Total mappings: {len(high_df) + len(low_df)}")

print("\n=== HIGH CONFIDENCE BY COUNTRY ===")
print(high_df['home_country'].value_counts().head(10))

print("\n=== LOW CONFIDENCE BY COUNTRY ===")
print(low_df['home_country'].value_counts().head(10))